version: "3.9"

name: taxlaw-rag-deps

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:11434/api/tags >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command: >
      "ollama pull llama3.1:8b &&
       ollama pull mxbai-embed-large"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: "no"

  chroma:
    image: ghcr.io/chroma-core/chroma:1.0.0
    container_name: chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    environment:
      - ANONYMIZED_TELEMETRY=false
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/api/v1/heartbeat >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  ollama_models:
  chroma_data: